# Generated by Django 2.1.7 on 2019-03-24 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(max_length=80)),
                ('start_time', models.DateTimeField(unique=True)),
                ('end_time', models.DateTimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='room2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(max_length=80)),
                ('start_time', models.DateTimeField(unique=True)),
                ('end_time', models.DateTimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='room3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(max_length=80)),
                ('start_time', models.DateTimeField(unique=True)),
                ('end_time', models.DateTimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('id_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('position', models.CharField(choices=[('S', 'Students'), ('T', 'Teachers'), ('A', 'Admins')], default='S', max_length=1)),
                ('department', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='room3',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.User'),
        ),
        migrations.AddField(
            model_name='room2',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.User'),
        ),
        migrations.AddField(
            model_name='room1',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.User'),
        ),
    ]
